# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxSwift-Tuts' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxSwift-Tuts
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'

  target 'RxSwift-TutsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RxSwift-TutsUITests' do
    inherit! :search_paths
    # Pods for testing
  end
end
